version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: banco
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: userA
      MYSQL_PASSWORD: firewall
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - neo
  app:
    build: .
    ports:
      - 80:8000
    networks:
      - neo   

networks:
  neo:
