name: simple crud
on: push

jobs:
  build:
    name: Laravel Crud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: infohouse/crudLaravel/tree/master/.github/actions/composer
